### ISSUE TITLE
504 Error on folder delete

### ISSUE THREAD

**Issue by gewondjan** [byuitechops/build-file-structure#6]
```
Message:

DELETE https://byui.instructure.com/api/v1/folders/730995?force=true failed with: 504

Stack:
Error: DELETE https://byui.instructure.com/api/v1/folders/730995?force=true failed with: 504 at got.then.res (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-api-wrapper\canvas.js:112:15) at at process._tickCallback (internal/process/next_tick.js:189:7)

Location:
build-file-structure\main.js
```

**Comment by gewondjan** [comment]
It happened for me twice.  Here is one of the courses that it happened on: https://trello.com/c/tjx0jhKZ

**Comment by gewondjan** [comment]
And this is the other one: https://trello.com/c/BrhPqLBH

**Comment by danverde** [comment]
D2L OU: 470142 & 21786

**Comment by danverde** [comment]
moved to https://github.com/byuitechops/canvas-api-wrapper/issues/45
